# dvc.yaml

stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - data/raw/household_power_consumption_hourly.csv
      - src/preprocess.py
    params:
      - preprocess
      - train.features
    outs:
      - data/processed

  train:
    foreach: ${train.models}
    do:
      cmd: python src/train.py --model-name "${item.name}"
      deps:
        - data/processed
        - src/train.py
      params:
        - train.features
        - validation
        - train.models # Depends on the whole list
      outs:
        - models/${item.file_name}

  evaluate:
    foreach: ${train.models}
    do:
      cmd: python src/evaluate.py --model-name "${item.name}"
      deps:
        - models/${item.file_name}
        - data/processed
        - src/evaluate.py
      params:
        - validation
        - preprocess.target_column
        - train.models
      metrics:
        - metrics/${item.name}_metrics.json:
            cache: false
      plots:
        - metrics/validation_plots/${item.name}_residuals_over_time.png:
            cache: false
        - metrics/validation_plots/${item.name}_residuals_histogram.png:
            cache: false