# params.yaml

preprocess:
  target_column: 'Global_active_power'
  test_split_ratio: 0.2

train:
  features:
    - 'Global_reactive_power'
    - 'Voltage'
    - 'Global_intensity'
    - 'Sub_metering_1'
    - 'Sub_metering_2'
    - 'Sub_metering_3'
    - 'hour_of_day'
    - 'day_of_week'
    - 'month'
    - 'year'
  
  # A list of models to train and evaluate
  models:
    - name: 'XGBoostRegressor'
      file_name: 'xgb_model.pkl'
      params:
        objective: 'reg:squarederror'
        n_estimators: 1000
        learning_rate: 0.05
        max_depth: 6
        min_child_weight: 1
        gamma: 0.1
        reg_alpha: 0.005
        reg_lambda: 1
        subsample: 0.8
        colsample_bytree: 0.8
        random_state: 42

    - name: 'RandomForestRegressor'
      file_name: 'rf_model.pkl'
      params:
        n_estimators: 200
        max_depth: 15
        min_samples_split: 5
        min_samples_leaf: 2
        max_features: 'sqrt'
        bootstrap: true
        oob_score: true
        random_state: 42
        n_jobs: -1

    - name: 'LightGBMRegressor'
      file_name: 'lgbm_model.pkl'
      params:
        boosting_type: 'gbdt'
        objective: 'regression_l1'
        n_estimators: 1000
        learning_rate: 0.05
        num_leaves: 31
        max_depth: -1
        reg_alpha: 0.1
        reg_lambda: 0.1
        colsample_bytree: 0.8
        subsample: 0.8
        random_state: 42
        n_jobs: -1

# --- THIS SECTION WAS MISSING ---
validation:
  run_tcv: true
  tcv_splits: 5
  plots_dir: 'metrics/validation_plots'